name = "hms-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

[vars]
BETTER_AUTH_URL = "https://hms-api.sethstha.workers.dev"
BETTER_AUTH_TRUSTED_ORIGINS = "https://hms-admin-sethstha.pages.dev"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
